name: Node + PostgreSQL CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      # -------------------------
      # CHECKOUT
      # -------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------------
      # CREATE ENV FILE
      # -------------------------
      - name: Create .env from GitHub Environment
        run: |
          touch .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_TYPE=${{ secrets.DB_TYPE }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          
      # -------------------------
      # SETUP NODE
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      # -------------------------
      # INSTALL + BUILD
      # -------------------------
      - name: Install dependencies
        run: npm install

      - name: Run Test
        run: npm test || echo "No tests found"

      - name: Debug SSH key
        run: |
             echo "${{ secrets.REMOTE_SSH_KEY }}" | head -n 2
            
      # -------------------------
      # DEPLOY
      # -------------------------
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         password: ${{ secrets.REMOTE_PASSWORD }}
         port: 2222
         source: "."
         target: "/home/inventam/Desktop/mynodeapp"

      # -------------------------
      # REMOTE EXECUTION
      # -------------------------
      - name: Run remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 2222
          script: |
            cd /home/inventam/Desktop/mynodeapp
            npm install
            pm2 stop myapp || true
            pm2 reload myapp || pm2 start -n myapp npm -- start