</> YAML

name: node+postgres

on:
    push:
        branch:
            - main

Jobs:
    test:
        runs-on: ubuntu:latest
        service:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: db
                    POSTGRES_PASSWORD: 123456
                    POSTGRES_DB: db
                    ports:
                        5432:5432
steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: install dependecies
      run: npm install
    - name: wait for db
      run: sleep 5
    - name: run tests
      run: npm test
