name: Node + PostgreSQL CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      # -------------------------
      # CHECKOUT
      # -------------------------
      - name: Checkout repo
        uses: actions/checkout@v4


      # -------------------------
      # SETUP NODE
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.22.2'
          cache: 'npm'

      # -------------------------
      # INSTALL + BUILD
      # -------------------------
      - name: Install dependencies
        run: npm install

      - name: Run Test
        run: npm test || echo "No tests found"

      - name: Debug SSH key
        run: |
             echo "${{ secrets.REMOTE_SSH_KEY }}" | head -n 2
            
      # -------------------------
      # DEPLOY
      # -------------------------
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         key: ${{ secrets.REMOTE_SSH_KEY }}
         port: 22
         source: "."
         target: "/home/ec2-user/mynode"

      # -------------------------
      # REMOTE EXECUTION
      # -------------------------
      - name: Run remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            export PATH="/home/ec2-user/.nvm/versions/node/v22.22.2/bin:$PATH"
            cd /home/ec2-user/mynode
            npm install
            pm2 stop myapp || true
            pm2 reload myapp || pm2 start -n myappserver npm -- start
